version: "3.8"

services:
  morphic:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - SEARXNG_API_URL=http://searxng:8080
      - USE_LOCAL_REDIS=false
      - NEXT_PUBLIC_ENABLE_SAVE_CHAT_HISTORY=false
      - OPENAI_COMPATIBLE_API_KEY=sk-zhlcboxuerkkmlarpilwzxhixieyumsiokgagcqwfbrfgkxr
      - OPENAI_COMPATIBLE_API_BASE_URL=https://api.siliconflow.cn/v1
      - NEXT_PUBLIC_OPENAI_COMPATIBLE_MODEL=Pro/deepseek-ai/DeepSeek-V3
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - SEARXNG_PORT=${SEARXNG_PORT}
      - SEARXNG_BIND_ADDRESS=${SEARXNG_BIND_ADDRESS}
      - SEARXNG_IMAGE_PROXY=${SEARXNG_IMAGE_PROXY}
      - SEARXNG_LIMITER=${SEARXNG_LIMITER}
      - SEARXNG_DEFAULT_DEPTH=${SEARXNG_DEFAULT_DEPTH}
      - SEARXNG_MAX_RESULTS=${SEARXNG_MAX_RESULTS}
      - SEARXNG_ENGINES=${SEARXNG_ENGINES}
      - SEARXNG_TIME_RANGE=${SEARXNG_TIME_RANGE}
      - SEARXNG_SAFESEARCH=${SEARXNG_SAFESEARCH}
      - NEXT_PUBLIC_ENABLE_SHARE=${NEXT_PUBLIC_ENABLE_SHARE}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - default
    depends_on:
      searxng:
        condition: service_started

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - ./searxng-settings.yml:/etc/searxng/settings.yml:ro
      - ./searxng-ustats.yml:/etc/searxng/ustats.yml:ro

networks:
  default:
    driver: bridge
